version: '2'

volumes:
  nexus-data: {} 
  jenkins-data: {} 
  sonar-data: {} 
  postgres-data: {} 

networks:
  devnet:
    driver: bridge

services:
 nexus:
  image: sonatype/nexus3
  container_name: nexus
  environment:
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  ports:
    - "8081:8081"
  networks:
    - devnet
  volumes:
    - "nexus-data:/nexus-data"

 jenkins:
  image: jenkins/jenkins:lts-jdk11
  container_name: jenkins
  ports:
    - "8080:8080"
  networks:
    - devnet
  volumes:
    - "jenkins-data:/var/jenkins_home"
 
 sonarqube:
  image: sonarqube:lts
  container_name: sonarqube
  restart: always
  ports:
    - "9000:9000"
  networks:
    - devnet
  depends_on:
    - sonardb
  links:
    - sonardb
  environment:
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
    - SONARQUBE_JDBC_USERNAME=sonar
    - SONARQUBE_JDBC_PASSWORD=sonar
  volumes:
    - "sonar-data/:/var/lib/sonar"

 sonardb:
  networks:
    - devnet
  image: postgres:9.6.1
  container_name: postgres
  restart: always
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar
   - POSTGRESQL_DB=sonar
  ports:
    - "5432:5432"
  volumes:
    - "postgres-data:/var/lib/postgresql"
